### PR TITLE
added the error codes as comments in the errors.ts file

### PR DESCRIPTION
**Pull request by nitzantomer**
because sometimes you want to search by an error code and you don't remember that 409 is conflict...

### CODE REVIEW

**Review by liorama — APPROVED** [review]
@nitzantomer Nice.
Do you think maybe changing the name to let say `404_NOT_FOUND` would be better (so it's clear any place it appears in the code base)?

I restarted the travis built since it failed and I couldn't see a good reason why that'll happen.

**Comment by nitzantomer** [comment]
@liorama 
but it says that before the comment:
> NOT_FOUND, // 404
isn't that what you want? or am i missing something?

**Comment by liorama** [comment]
@nitzantomer I meant to change the key name, so instead of:
`CODES.Conflict` we'll do `CODES.409_conflict`, so when looking at:
`new MarketplaceError(CODES.Conflict.code, CODES.Conflict.types[key], "Conflict", message)`
You'd know what the code is without following into the implementation. Also, a descriptive name is better than a comment.

**Comment by nitzantomer** [comment]
@liorama 
oh, there's no need for that, imo.
the use of the `MarketplaceError` constructor is internal to this file.
i added the codes because you sometimes need to find out what's the error with code `4095` (for example) because it's part of an error the clients received.
it was harder for find out if the codes weren't in the code

**Pull request merged**
